### ISSUE TITLE
Where has time gone?

### ISSUE THREAD

**Issue by rrichardson** [uluadist/ulua#1]
I am looking for the time module that is enumerated here: http://ulua.io/native_packages.html 
and  described here: http://scilua.org/time.html 

When I run the ulua/lua and require('time') it fails to find it.  I also see no such thing in Luarocks.  
Any hints would be appreciated. 

Thanks

**Comment by stepelu** [comment]
Can you please point me to the exact error?

Also, did you install the time package (via `upkg add time` or `pkg.install('time')`) ?

**Comment by rrichardson** [comment]
Ah ha!  I misunderstood the documentation. I had assumed it was built in.  upkg add time worked. 
Thanks!
