### ISSUE TITLE
Can ulua be used to install non lua packages (like docs and others)

### ISSUE THREAD

**Issue by offray** [uluadist/ulua#4]
Thanks for your work on ulua. I like the idea of semantic versioning for packages and using the file system as a data base, allowing multiple versions for a package, in a similar way to Gobo Linux or Nix. 

I wonder if ulua could be used for installing non-lua packages, like documentation or other software. Basically the scenario I'm imagining is that someone uses a one liner to install an ulua based tool that is able to talk with external installers, like Nix for Linux/Mac or Scoop/Chocolatey for Windows (or even install them), and after that use this tool to launch particular services. 

For example, I want to provide non-coders with a particular [Fossil](http://fossil-scm.org/) repository so, after they have ran the one liner, they can open a console and type something like `upgk load repo-name` and the system will check if Fossil is installed (if not it will go to platform specific external package manager and install it), then it will run the cloning command, and finally launch the local Fossil web ui and open the browser there. Nix offers something similar but is only for Unix like operative systems and non Lua scriptable.

I'm willing to experiment on that, but I would like to know better if ulua/upkg are a good approach for the previous scenario. Any pointers on how to start are also appreciated.

Cheers,

**Comment by stepelu** [comment]
Hi, I am not sure I fully understand your use case, but the ULua package manager is oblivious to the content of packages as long as the specs (http://ulua.io/specs.html) are satisfied.
You could start by checking how the pkg module works: https://github.com/uluadist/lua-pkg
You will then have to modify it accordingly to your requirements.
Also, the other requirement is a "repo" file that contains info on all the available packages.
In the case of ULua it's generated (a bit automatically and a bit manually) using https://github.com/uluadist/lua-pkg-dev but I am unsure you would find that info useful, aside from understanding the structure of the repo file...

**Comment by offray** [comment]
Thanks,

Once started, I think that the project will be using Zero Install [1],
but ulua will be one of the multiplatform packages we will bring into
the mix. Basically because it already allows us to interact with other
native package managers and once ulua is installed, it will bring
multi-platform scriptability that we need.

[1] https://0install.net/

Cheers,
